// Copyright 2018 Parker Heindl. All rights reserved.
// Licensed under the MIT License. See LICENSE.md in the
// project root for information.
//
package header

import (
	"testing"

	"github.com/heindl/goethe/utilities"
	"github.com/stretchr/testify/assert"
)

func TestRender(t *testing.T) {

	mod, err := utilities.ReadModule(".")
	assert.NoError(t, err)

	mod.PackagePathFilters = append(mod.PackagePathFilters, "_test")

	b, err := Render(mod)
	assert.NoError(t, err)

	expected := `
[//]: # (Code generated by goethe DO NOT EDIT)\n# goethe

*v0.0.1* | *September 25, 2018*
#### Statically generate a github flavored README.md from a Go module.

This program parses your module directory for license, installation and command data, and generates a Github README.md file that upholds best practices.

It is **very unstable** right now.

Go1.11 modules are required, and this version only looks for a [Cobra Command](https://github.com/spf13/cobra), for documentation information.

Future versions will support Godocs, other command line helpers, and distribution and deployment tools. It will hopefully save time for both the reader and writer of open source code by automatically generating consistent documentation.
`
	assert.Equal(t, expected, string(b))
}
